#resolver: lts-6.30
resolver: lts-7.21

packages:
- '.'

# - location: ../flat
#   extra-dep: true

# - location: ../model
#   extra-dep: true

- location: ../zm
  extra-dep: true

extra-deps:
- model-0.3
- flat-0.3
- cryptonite-0.22
