resolver: lts-6.0

packages:
- '.'
# - ../flat
# - ../model
#- ../typed
- location: https://github.com/tittoassini/flat/archive/master.zip
- location: https://github.com/tittoassini/model/archive/master.zip
- location: https://github.com/tittoassini/typed/archive/master.zip
